### PR TITLE
Make type checking optional

### LINKED ISSUE #41: Should strict include check_argument_types?
https://github.com/mauke/Function-Parameters/blob/cfb871f898e9a7f3bb3c7c97ec824e6659c62181/lib/Function/Parameters.pm#L268-L271

Should this section here also set `check_argument_types`? The use case is I'd like to be able to do
```perl
use Function::Parameters qw(:lax)
```
and have `Function::Parameters` be effectively a no-op. I could send a PR but this might be a breaking change for existing users.

Any thoughts?

### PR DESCRIPTION
**Pull request by ccakes**
This is related to #25 and the performance impact of type checking.

I don't really love this implementation but it does work. This PR is mostly to act as a proposal to build on rather than a final version. I arbitrarily selected `Devel::StrictMode` as the toggle but that could just as easily be an environment variable.

Thoughts? Is this type of approach something that you'd be ok with? Alternatively if `Function::Parameters` resolved [this issue](https://github.com/mauke/Function-Parameters/issues/41) and if `Return::Type` merged in [#4](https://github.com/tobyink/p5-return-type/pull/4) then we probably wouldn't need the import shennanigans at all

### CODE REVIEW

**Comment by mohawk2** [comment]
I think this is a definite step in the right direction. Could you make the CI pass? There's no POD on the new module, and it's not in the MANIFEST. Most importantly, what difference does it make to runtime performance? Could you make a benchmark?

**Comment by ccakes** [comment]
Sure - can do. It's been a busy week but should be able to get back to this in the next few days

**Comment by ccakes** [comment]
Sorry for the lack of activity here!

I added some POD to `GraphQL::MaybeTypeCheck` to explain whats happening there. In terms of benchmarks, so far I haven't really struggled with the runtime performance of this so I don't have any existing benchmark code. My main struggle was the time taken to parse/build the schema which this does solve.

@chazmcgarvey do you have any existing benchmark code you could run against this branch and see how it fares?

**Comment by ccakes** [comment]
@mohawk2 since there's not been a volunteer I thought I'd have a stab at just benchmarking some of the test suite.

<details>
<summary>benchmark.pl</summary>

```perl
=for comment

Schema and query copy-pasted from t/execution-execute.t (subtest 'executes arbitrary code')

=cut

use Benchmark;

use GraphQL::Schema;
use GraphQL::Type::Object;
use GraphQL::Type::Scalar qw($String $Int $Boolean);
use GraphQL::Execution qw(execute);
use GraphQL::Language::Parser qw(parse);

###########
# Prep schema
my ($deep_data, $data);
$data = {
  a   => sub {'Apple'},
  b   => sub {'Banana'},
  c   => sub {'Cookie'},
  d   => sub {'Donut'},
  e   => sub {'Egg'},
  f   => 'Fish',
  pic => sub {
    my $size = shift;
    return 'Pic of size: ' . ($size || 50);
  },
  deep    => sub {$deep_data},
  promise => sub { FakePromise->resolve($data) },
};

$deep_data = {
  a      => sub {'Already Been Done'},
  b      => sub {'Boring'},
  c      => sub { [ 'Contrived', undef, 'Confusing' ] },
  deeper => sub { [ $data, undef, $data ] }
};

my ($DeepDataType, $DataType);
$DataType = GraphQL::Type::Object->new(
  name   => 'DataType',
  fields => sub {
    {
      a   => {type => $String},
      b   => {type => $String},
      c   => {type => $String},
      d   => {type => $String},
      e   => {type => $String},
      f   => {type => $String},
      pic => {
        args    => {size => {type => $Int}},
        type    => $String,
        resolve => sub {
          my ($obj, $args) = @_;
          return $obj->{pic}->($args->{size});
        }
      },
      deep    => {type => $DeepDataType},
      promise => {type => $DataType},
    }
  }
);

$DeepDataType = GraphQL::Type::Object->new(
  name   => 'DeepDataType',
  fields => {
    a      => {type => $String},
    b      => {type => $String},
    c      => {type => $String->list},
    deeper => {type => $DataType->list},
  }
);

my $schema = GraphQL::Schema->new(query => $DataType);

my $doc = <<'EOF';
query Example($size: Int) {
  a,
  b,
  x: c
  ...c
  f
  ...on DataType {
    pic(size: $size)
    promise {
      a
    }
  }
  deep {
    a
    b
    c
    deeper {
      a
      b
    }
  }
}
fragment c on DataType {
  d
  e
}
EOF
my $ast = parse($doc);

# Count iterations/sec
timethis(-5, sub { execute($schema, $ast, $data, undef, {size => 100}, 'Example') });
```

</details>

Running this I get the following results on a ~3yr old Macbook

```
$ PERL_STRICT=1 perl -Ilib benchmark.pl
Subroutine UNIVERSAL::ReturnType redefined at local/lib/perl5/Return/Type.pm line 111.
Subroutine UNIVERSAL::_ATTR_CODE_ReturnType redefined at /Users/cdaniel/.plenv/versions/5.26.3/lib/perl5/5.26.3/Attribute/Handlers.pm line 129.
timethis for 5:  6 wallclock secs ( 5.37 usr +  0.02 sys =  5.39 CPU) @ 425.79/s (n=2295)

$ perl -Ilib benchmark.pl
timethis for 5:  5 wallclock secs ( 5.43 usr +  0.02 sys =  5.45 CPU) @ 1618.35/s (n=8820)
```

That's a fairly substantial different but there are two main issues I see with this PR that'd prevent it from being ready to merge

1. the subroutine redefined warnings in strict mode; and
2. the fact that the default behaviour has changed (ie strict is off by default)

I don't really know how to fix the first one - it's probably possible by generating the no-op attribute handler without `Attribute::Handlers` I guess? The second option is simple to fix, we just need to decide to either change the default (not my preference) or decide on a signal to disable the checks.. eg `$ENV{GRAPHQL_PERL_LOOSE_TYPES=1}`?

**Comment by mohawk2** [comment]
@ccakes Thanks for your effort on this! If you can make the benchmark be a separate commit on this PR I'd really like to cherry-pick and incorporate it in the repo now.

As for how to solve the general problem of type-checking vs testing vs production, a strategy that might work would be for the type-checking to only be on in an author-test under `xt`, which would run the test suite with it on. One way to turn it on/off might actually be a source-filter, since it rather looks like the authors of the repos aren't interested in those PRs.

If one is considering that, then actually switching to using Type::Params as suggested by Toby Inkster back at the start of this journey (http://blogs.perl.org/users/ed_j/2017/05/graphql-perl---a-graphql-reference-implementation-in-perl.html#comment-1786772) might be the best way forward.

**Comment by ccakes** [comment]
@mohawk2 just added in ea305eb

Personally I'm fine with the current setup. `Devel::StrictMode` enables itself for release testing which is ok for me but if any users of the module have come to rely on the type checking this might be an unwelcome change.

I'm also not sure exactly how to override the `Return::Type` behaviour that doesn't leak outside scope of this module. I haven't used attributes much, or source filters at all, so some pointers for next steps on that front would be appreciated 😊

**Comment by mohawk2** [comment]
I've just cherry-picked your benchmark onto master, and pushed it (though I renamed it into `util/`). I've taken the liberty of rebasing and force-pushing to your branch just to reflect that and avoid clashes/confusion.

**Comment by mohawk2** [comment]
I'm liking the idea of this more and more. I think at least Role::FieldsOutput doesn't need to load the new module at all and the old one can safely be deleted.

**Comment by mohawk2** [comment]
Question (because you've looked at this more than me): does there need to be a `UNIVERSAL::ReturnType` defined? That seems like it could cause problems for other modules if they use Return::Type.

To address your other point: source-filtering is considered a bad idea these days, so I think we should go in the direction you're suggesting.

**Comment by ccakes** [comment]
> Question (because you've looked at this more than me): does there need to be a `UNIVERSAL::ReturnType` defined?

There definitely shouldn't be. After spending some time on this today I think the only way we can get around this is to define our own attribute in a package and make it the parent to all `GraphQL::` packages that need it. I couldn't figure out a way to "inject" an attribute into an arbitrary package namespace, it seems to need to be in the ISA chain somewhere.

My current experiment (which does work) is to replace `GraphQL::MaybeTypeCheck` with `GraphQL::Base` and make it the parent of all our packages.

This seems like a reasonable approach. Right now it's only handling the type-check switch but there may be other things that'd be easier implemented with a shared base class? 🤷‍♂️ 

**EDIT:** There's actually no reason it needs to be `GraphQL::Base`..  the existing package can just as easily add itself to `@{"$caller::ISA"}`.

**Review by mohawk2 — APPROVED** [review]

**Pull request merged**
