### PR TITLE
instrumentation feature for performance monitoring

### PR DESCRIPTION
**Pull request by taiyoh**
Hi

I want hook point for monitoring performance of GraphQL request like 'instrumentation' in graphql-ruby.
this pr is implementation of instrumentation.
please review this.

best regards.
thanks.

### CODE REVIEW

**Comment by mohawk2** [comment]
Hi @taiyoh, thanks for the PR!

# Things I am very keen on

* this concept - performance monitoring is of course critical for scalable software
* the fact that it's got tests

# Things that I feel need work

## Special cases

You've special-cased `query_instruments` and `mutation_instruments`. In the end, all queries and mutations are just fields of a type, so these special cases could usefully be removed.

## Mutations

The API you've given uses mutations: you create the objects, then mutate them with `register_resolver`. Also your test instrumenters mutate a quasi-global `$stacktrace`. This is a thing I've worked hard to avoid, and I even eliminated one mutation that `graphql-js` does: mutating `context.errors` to pass back errors.

Can you figure out a way to include the instrumentation at instantiation time? My gut says your `GraphQL::Role::Instrument` isn't entirely necessary, but the concept of roles here has legs. Possibilities:

* A `GraphQL::Plugin::Instrument` API, and figured a way to get a subclass injected at instantiation time
* Something like a `with_roles` (cf http://mojolicious.org/perldoc/Mojo/Collection#with_roles), so that you'd define a role that gets added to let's say fields, or maybe types
* You could have an `around` (cf https://metacpan.org/pod/Class::Method::Modifiers#around-method(s)-=%3E-sub-%7B-...-%7D;) for all resolvers, both the default one (either in `GraphQL::Execution` or the supplied one to `execute`) and fields' resolvers. This could simply be another param to `execute`, since that is the place from which all resolvers are called.

Of these, I favour the last: another parameter to `execute`, which is a resolver-wrapper. If given, it will be called with the original code-ref as first param, then all the other params. Your test version would be welcome to mutate a quasi-global as currently, since pragmatically that is the best option. The wrapper could then call the original. Such a thing might look like:

```
execute(
  ...
  sub {
    my $orig = shift;
    # get current high-res time
    my $ret = $orig->(@_);
    # calculate duration, record it somewhere
    $ret;
  },
);
```

One important benefit is there is much less code: no new role would be needed!

## Not entirely beautiful commits

This is one I learned fairly recently, and have come to value a great deal. This is much easier to achieve if you work on a branch, but is completely achievable here still using your existing `master`. The key is to `rebase -i origbranch`, which here might be `upstream/master` (you'd need to:

```
git remote add upstream git@github.com:graphql-perl/graphql-perl.git
git fetch --all
```

to make that possible). You would then merge together any fixups, such as fixing typos (especially using the `fixup` command), so that your final set of commits was a set of logical changes that each makes sense by itself, and moves your code to where you want to end up. You would then force-push to the relevant branch in this case `origin/master`.

# Final thoughts

The reason I am making these suggestions on how to proceed is because I have occasionally submitted PRs myself, and a maintainer thanked me, then did the idea their own way, wasting my time. You might gather from the above that I could probably implement my above idea fairly easily, but that would be stealing your idea. In any case, I am busy implementing `GraphQL::Plugin::Convert::OpenAPI`!

Let me know how you would like to proceed. I would like best of all if you implement the above suggestions since yours is a great idea!

**Comment by mohawk2** [comment]
Hi @taiyoh, are you interested in updating your PR?

**Comment by taiyoh** [comment]
Thank you for your review and sorry for late late reply. 
First of all, I realized that I misunderstood about resolver implementation.
Second, my aim for monitoring is detecting long time resolving field, but watching total response time is more than important.
Your advice is accurate.
So I withdraw this PR for no needs.
Thank you so much. :bowing_man:

**Comment by mohawk2** [comment]
Thanks for clarifying. Please feel free to open issues to ask questions, or submit other PRs, else come on `#graphql-perl` to chat.

An additional idea came to me just now, to achieve what you're after: just supply a default field-resolver that is based on the one in `GraphQL::Execution` that does the normal dispatching stuff, but also records times. Check out https://p3rl.org/GraphQL::Plugin::Convert::OpenAPI for inspiration. No core code changes needed at all!

**Pull request closed without merging**
