### PR TITLE
block strings

### PR DESCRIPTION
**Pull request by chazmcgarvey**
Two commits.

First fixes what seems to be a bug where string literals are not unescaped; the test added in dd7dc6e seems wrong... but I'm willing to be proven I'm stupid.

Second adds support for [block strings](https://facebook.github.io/graphql/June2018/#sec-String-Value) from the June 2018 spec.

Sorry... maybe you have some of this work done already in a WIP branch. Should have checked before coding so much, but actually I regret nothing. I was having fun.

### CODE REVIEW

**Comment by mohawk2** [comment]
This is really good stuff! One tiny nit: I'd much prefer the test filenames be like `file-name` not `fileName` - bit more Perl-ish to me.

Do you feel like going one step further, and eliminating the `description` as "meaningful comments" stuff, so it's only for `"""`-delineated stuff? That's one of the main ways the "real" GQL spec has got ahead of the Perl implementation.

I'll be happy to merge this PR if you can just rename the filename as per para 1, and whether you want to do para 2 at all, or as a separate PR, is totally up to you :-)

**Comment by chazmcgarvey** [comment]
Great nits. I'll be happy to make those changes tonight.

**Comment by mohawk2** [comment]
@chazmcgarvey Thanks, as you can see I've merged this. I have squashed together the last two commits, so you'll need to make sure your `master` reflects that - I think just `git pull` will do that as normal, unless you `pull`ed it in the moments between my click and the force-push :-)

Do you think you'll be having a go at the "meaningful comments" removal, or shall I?

**Comment by chazmcgarvey** [comment]
@mohawk2 Yeah I didn't finish, but I just pushed up a work in progress (tests not passing, don't merge):

https://github.com/chazmcgarvey/graphql-perl/commit/bc689e3a427ad4135c7bcb1d65eb8a096a30ed1e

I'll get back to it when I get more tuits. My code here is lacking because it doesn't generate the descriptions (for `to_doc`) like the reference implementation yet, and I haven't got all the tests working, perhaps because I've added more recent versions of kitchen sink.

Anyway, I do plan to return to this within a couple weeks, but I won't be offended if you want to have a go yourself (either continuing on this commit or from scratch).

**Comment by mohawk2** [comment]
I've made `to_doc` produce new-style descriptions while still allowing old-style ones, to allow converting. I also updated both kitchen-sinks to current. These changes have all just been released as 0.32. Let me know if you have any problems!

The next version is where I intend to zap the "meaningful comments" (or merge your work if you get there first :-) ) as that should simplify the grammar nicely.

**Pull request merged**
